const STATIONS = [
  {
    "name": "J.F. Kennedy",
    "line": "A",
    "props": {
      "Correspondance avec un Chronosbus": false,
      "Terminus d'une ligne de Métro ou d'un Chronobus ": true,
      "Station aérienne": false,
      "Station au sud de la Vilaine": false,
      "Station au nord de la Vilaine": true,
      "Station hors Rennes": false,
      "Station à Rennes": true,
      "Nom composé d'une personne": true,
      "Fait partie du top 10 des stations les plus fréquentées": false,
      "Commence par une voyelle": false,
      "Ne contient pas la lettre A": true,
      "Ne contient pas la lettre E": false,
      "Ne contient pas la lettre I": true,
      "Contient la lettre Y": true,
      "Contient des lettres doublées": true,
      "Nom commençant par la lettre L": false,
      "Nom en un seul mot": false,
      "Correspondancevec un parking relais": true,
      "Moins d'1km d'un campus universitaire": true,
      "Moins d'1km d'un centre commercial": false,
      "Moins d'1km d'un hôpital public": false,
      "Moins d'1km d'un parc / jardin": false
    }
  },
  {
    "name": "Villejean-Université",
    "line": "A",
    "props": {
      "Correspondance avec un Chronosbus": true,
      "Terminus d'une ligne de Métro ou d'un Chronobus ": false,
      "Station aérienne": false,
      "Station au sud de la Vilaine": false,
      "Station au nord de la Vilaine": true,
      "Station hors Rennes": false,
      "Station à Rennes": true,
      "Nom composé d'une personne": false,
      "Fait partie du top 10 des stations les plus fréquentées": true,
      "Commence par une voyelle": false,
      "Ne contient pas la lettre A": false,
      "Ne contient pas la lettre E": false,
      "Ne contient pas la lettre I": false,
      "Contient la lettre Y": false,
      "Contient des lettres doublées": true,
      "Nom commençant par la lettre L": false,
      "Nom en un seul mot": false,
      "Correspondancevec un parking relais": true,
      "Moins d'1km d'un campus universitaire": true,
      "Moins d'1km d'un centre commercial": false,
      "Moins d'1km d'un hôpital public": true,
      "Moins d'1km d'un parc / jardin": false
    }
  },
  {
    "name": "Pontchaillou",
    "line": "A",
    "props": {
      "Correspondance avec un Chronosbus": false,
      "Terminus d'une ligne de Métro ou d'un Chronobus ": false,
      "Station aérienne": true,
      "Station au sud de la Vilaine": false,
      "Station au nord de la Vilaine": true,
      "Station hors Rennes": false,
      "Station à Rennes": true,
      "Nom composé d'une personne": false,
      "Fait partie du top 10 des stations les plus fréquentées": false,
      "Commence par une voyelle": false,
      "Ne contient pas la lettre A": false,
      "Ne contient pas la lettre E": true,
      "Ne contient pas la lettre I": false,
      "Contient la lettre Y": false,
      "Contient des lettres doublées": true,
      "Nom commençant par la lettre L": false,
      "Nom en un seul mot": true,
      "Correspondancevec un parking relais": false,
      "Moins d'1km d'un campus universitaire": true,
      "Moins d'1km d'un centre commercial": false,
      "Moins d'1km d'un hôpital public": true,
      "Moins d'1km d'un parc / jardin": false
    }
  },
  {
    "name": "Anatole France",
    "line": "A",
    "props": {
      "Correspondance avec un Chronosbus": true,
      "Terminus d'une ligne de Métro ou d'un Chronobus ": false,
      "Station aérienne": false,
      "Station au sud de la Vilaine": false,
      "Station au nord de la Vilaine": true,
      "Station hors Rennes": false,
      "Station à Rennes": true,
      "Nom composé d'une personne": true,
      "Fait partie du top 10 des stations les plus fréquentées": false,
      "Commence par une voyelle": true,
      "Ne contient pas la lettre A": false,
      "Ne contient pas la lettre E": false,
      "Ne contient pas la lettre I": true,
      "Contient la lettre Y": false,
      "Contient des lettres doublées": false,
      "Nom commençant par la lettre L": false,
      "Nom en un seul mot": false,
      "Correspondancevec un parking relais": false,
      "Moins d'1km d'un campus universitaire": false,
      "Moins d'1km d'un centre commercial": false,
      "Moins d'1km d'un hôpital public": true,
      "Moins d'1km d'un parc / jardin": false
    }
  },
  {
    "name": "Sainte-Anne",
    "lines": ["A","B"],
    "props": {
      "Correspondance avec un Chronosbus": false,
      "Terminus d'une ligne de Métro ou d'un Chronobus ": false,
      "Station aérienne": false,
      "Station au sud de la Vilaine": false,
      "Station au nord de la Vilaine": true,
      "Station hors Rennes": false,
      "Station à Rennes": true,
      "Nom composé d'une personne": true,
      "Fait partie du top 10 des stations les plus fréquentées": true,
      "Commence par une voyelle": false,
      "Ne contient pas la lettre A": false,
      "Ne contient pas la lettre E": false,
      "Ne contient pas la lettre I": false,
      "Contient la lettre Y": false,
      "Contient des lettres doublées": true,
      "Nom commençant par la lettre L": false,
      "Nom en un seul mot": false,
      "Correspondancevec un parking relais": false,
      "Moins d'1km d'un campus universitaire": true,
      "Moins d'1km d'un centre commercial": true,
      "Moins d'1km d'un hôpital public": false,
      "Moins d'1km d'un parc / jardin": true
    }
  },
  {
    "name": "République",
    "line": "A",
    "props": {
      "Correspondance avec un Chronosbus": true,
      "Terminus d'une ligne de Métro ou d'un Chronobus ": false,
      "Station aérienne": false,
      "Station au sud de la Vilaine": true,
      "Station au nord de la Vilaine": false,
      "Station hors Rennes": false,
      "Station à Rennes": true,
      "Nom composé d'une personne": false,
      "Fait partie du top 10 des stations les plus fréquentées": true,
      "Commence par une voyelle": false,
      "Ne contient pas la lettre A": true,
      "Ne contient pas la lettre E": false,
      "Ne contient pas la lettre I": false,
      "Contient la lettre Y": false,
      "Contient des lettres doublées": false,
      "Nom commençant par la lettre L": false,
      "Nom en un seul mot": true,
      "Correspondancevec un parking relais": false,
      "Moins d'1km d'un campus universitaire": true,
      "Moins d'1km d'un centre commercial": true,
      "Moins d'1km d'un hôpital public": false,
      "Moins d'1km d'un parc / jardin": true
    }
  },
  {
    "name": "Charles de Gaulle",
    "line": "A",
    "props": {
      "Correspondance avec un Chronosbus": true,
      "Terminus d'une ligne de Métro ou d'un Chronobus ": false,
      "Station aérienne": false,
      "Station au sud de la Vilaine": true,
      "Station au nord de la Vilaine": false,
      "Station hors Rennes": false,
      "Station à Rennes": true,
      "Nom composé d'une personne": true,
      "Fait partie du top 10 des stations les plus fréquentées": true,
      "Commence par une voyelle": false,
      "Ne contient pas la lettre A": false,
      "Ne contient pas la lettre E": false,
      "Ne contient pas la lettre I": true,
      "Contient la lettre Y": false,
      "Contient des lettres doublées": true,
      "Nom commençant par la lettre L": false,
      "Nom en un seul mot": false,
      "Correspondancevec un parking relais": false,
      "Moins d'1km d'un campus universitaire": false,
      "Moins d'1km d'un centre commercial": true,
      "Moins d'1km d'un hôpital public": false,
      "Moins d'1km d'un parc / jardin": false
    }
  },
  {
    "name": "Gares",
    "lines": ["A","B"],
    "props": {
      "Correspondance avec un Chronosbus": true,
      "Terminus d'une ligne de Métro ou d'un Chronobus ": false,
      "Station aérienne": false,
      "Station au sud de la Vilaine": true,
      "Station au nord de la Vilaine": false,
      "Station hors Rennes": false,
      "Station à Rennes": true,
      "Nom composé d'une personne": false,
      "Fait partie du top 10 des stations les plus fréquentées": true,
      "Commence par une voyelle": false,
      "Ne contient pas la lettre A": false,
      "Ne contient pas la lettre E": false,
      "Ne contient pas la lettre I": true,
      "Contient la lettre Y": false,
      "Contient des lettres doublées": false,
      "Nom commençant par la lettre L": false,
      "Nom en un seul mot": true,
      "Correspondancevec un parking relais": false,
      "Moins d'1km d'un campus universitaire": false,
      "Moins d'1km d'un centre commercial": true,
      "Moins d'1km d'un hôpital public": false,
      "Moins d'1km d'un parc / jardin": false
    }
  },
  {
    "name": "Jacques Cartier",
    "line": "A",
    "props": {
      "Correspondance avec un Chronosbus": true,
      "Terminus d'une ligne de Métro ou d'un Chronobus ": false,
      "Station aérienne": false,
      "Station au sud de la Vilaine": true,
      "Station au nord de la Vilaine": false,
      "Station hors Rennes": false,
      "Station à Rennes": true,
      "Nom composé d'une personne": true,
      "Fait partie du top 10 des stations les plus fréquentées": false,
      "Commence par une voyelle": false,
      "Ne contient pas la lettre A": false,
      "Ne contient pas la lettre E": false,
      "Ne contient pas la lettre I": false,
      "Contient la lettre Y": false,
      "Contient des lettres doublées": false,
      "Nom commençant par la lettre L": false,
      "Nom en un seul mot": false,
      "Correspondancevec un parking relais": false,
      "Moins d'1km d'un campus universitaire": false,
      "Moins d'1km d'un centre commercial": false,
      "Moins d'1km d'un hôpital public": false,
      "Moins d'1km d'un parc / jardin": false
    }
  },
  {
    "name": "Clémenceau",
    "line": "A",
    "props": {
      "Correspondance avec un Chronosbus": false,
      "Terminus d'une ligne de Métro ou d'un Chronobus ": false,
      "Station aérienne": false,
      "Station au sud de la Vilaine": true,
      "Station au nord de la Vilaine": false,
      "Station hors Rennes": false,
      "Station à Rennes": true,
      "Nom composé d'une personne": true,
      "Fait partie du top 10 des stations les plus fréquentées": false,
      "Commence par une voyelle": false,
      "Ne contient pas la lettre A": false,
      "Ne contient pas la lettre E": false,
      "Ne contient pas la lettre I": true,
      "Contient la lettre Y": false,
      "Contient des lettres doublées": false,
      "Nom commençant par la lettre L": false,
      "Nom en un seul mot": false,
      "Correspondancevec un parking relais": false,
      "Moins d'1km d'un campus universitaire": false,
      "Moins d'1km d'un centre commercial": false,
      "Moins d'1km d'un hôpital public": false,
      "Moins d'1km d'un parc / jardin": false
    }
  },
  {
    "name": "Henri Fréville",
    "line": "A",
    "props": {
      "Correspondance avec un Chronosbus": true,
      "Terminus d'une ligne de Métro ou d'un Chronobus ": true,
      "Station aérienne": false,
      "Station au sud de la Vilaine": true,
      "Station au nord de la Vilaine": false,
      "Station hors Rennes": false,
      "Station à Rennes": true,
      "Nom composé d'une personne": true,
      "Fait partie du top 10 des stations les plus fréquentées": true,
      "Commence par une voyelle": false,
      "Ne contient pas la lettre A": true,
      "Ne contient pas la lettre E": false,
      "Ne contient pas la lettre I": false,
      "Contient la lettre Y": false,
      "Contient des lettres doublées": true,
      "Nom commençant par la lettre L": false,
      "Nom en un seul mot": false,
      "Correspondancevec un parking relais": true,
      "Moins d'1km d'un campus universitaire": false,
      "Moins d'1km d'un centre commercial": true,
      "Moins d'1km d'un hôpital public": false,
      "Moins d'1km d'un parc / jardin": false
    }
  },
  {
    "name": "Italie",
    "line": "A",
    "props": {
      "Correspondance avec un Chronosbus": false,
      "Terminus d'une ligne de Métro ou d'un Chronobus ": false,
      "Station aérienne": false,
      "Station au sud de la Vilaine": true,
      "Station au nord de la Vilaine": false,
      "Station hors Rennes": false,
      "Station à Rennes": true,
      "Nom composé d'une personne": false,
      "Fait partie du top 10 des stations les plus fréquentées": false,
      "Commence par une voyelle": true,
      "Ne contient pas la lettre A": false,
      "Ne contient pas la lettre E": false,
      "Ne contient pas la lettre I": false,
      "Contient la lettre Y": false,
      "Contient des lettres doublées": false,
      "Nom commençant par la lettre L": false,
      "Nom en un seul mot": true,
      "Correspondancevec un parking relais": false,
      "Moins d'1km d'un campus universitaire": false,
      "Moins d'1km d'un centre commercial": true,
      "Moins d'1km d'un hôpital public": false,
      "Moins d'1km d'un parc / jardin": false
    }
  },
  {
    "name": "Triangle",
    "line": "A",
    "props": {
      "Correspondance avec un Chronosbus": false,
      "Terminus d'une ligne de Métro ou d'un Chronobus ": false,
      "Station aérienne": false,
      "Station au sud de la Vilaine": true,
      "Station au nord de la Vilaine": false,
      "Station hors Rennes": false,
      "Station à Rennes": true,
      "Nom composé d'une personne": false,
      "Fait partie du top 10 des stations les plus fréquentées": false,
      "Commence par une voyelle": false,
      "Ne contient pas la lettre A": false,
      "Ne contient pas la lettre E": false,
      "Ne contient pas la lettre I": false,
      "Contient la lettre Y": false,
      "Contient des lettres doublées": false,
      "Nom commençant par la lettre L": false,
      "Nom en un seul mot": true,
      "Correspondancevec un parking relais": false,
      "Moins d'1km d'un campus universitaire": false,
      "Moins d'1km d'un centre commercial": false,
      "Moins d'1km d'un hôpital public": true,
      "Moins d'1km d'un parc / jardin": false
    }
  },
  {
    "name": "Le Blosne",
    "line": "A",
    "props": {
      "Correspondance avec un Chronosbus": false,
      "Terminus d'une ligne de Métro ou d'un Chronobus ": false,
      "Station aérienne": false,
      "Station au sud de la Vilaine": true,
      "Station au nord de la Vilaine": false,
      "Station hors Rennes": false,
      "Station à Rennes": true,
      "Nom composé d'une personne": false,
      "Fait partie du top 10 des stations les plus fréquentées": false,
      "Commence par une voyelle": false,
      "Ne contient pas la lettre A": true,
      "Ne contient pas la lettre E": false,
      "Ne contient pas la lettre I": true,
      "Contient la lettre Y": false,
      "Contient des lettres doublées": false,
      "Nom commençant par la lettre L": true,
      "Nom en un seul mot": false,
      "Correspondancevec un parking relais": false,
      "Moins d'1km d'un campus universitaire": false,
      "Moins d'1km d'un centre commercial": false,
      "Moins d'1km d'un hôpital public": true,
      "Moins d'1km d'un parc / jardin": false
    }
  },
  {
    "name": "La Poterie",
    "line": "A",
    "props": {
      "Correspondance avec un Chronosbus": true,
      "Terminus d'une ligne de Métro ou d'un Chronobus ": true,
      "Station aérienne": true,
      "Station au sud de la Vilaine": true,
      "Station au nord de la Vilaine": false,
      "Station hors Rennes": false,
      "Station à Rennes": true,
      "Nom composé d'une personne": false,
      "Fait partie du top 10 des stations les plus fréquentées": false,
      "Commence par une voyelle": false,
      "Ne contient pas la lettre A": false,
      "Ne contient pas la lettre E": false,
      "Ne contient pas la lettre I": false,
      "Contient la lettre Y": false,
      "Contient des lettres doublées": false,
      "Nom commençant par la lettre L": true,
      "Nom en un seul mot": false,
      "Correspondancevec un parking relais": true,
      "Moins d'1km d'un campus universitaire": false,
      "Moins d'1km d'un centre commercial": false,
      "Moins d'1km d'un hôpital public": true,
      "Moins d'1km d'un parc / jardin": false
    }
  },
  {
    "name": "Cesson-Viasilva",
    "line": "B",
    "props": {
      "Correspondance avec un Chronosbus": true,
      "Terminus d'une ligne de Métro ou d'un Chronobus ": true,
      "Station aérienne": true,
      "Station au sud de la Vilaine": false,
      "Station au nord de la Vilaine": true,
      "Station hors Rennes": true,
      "Station à Rennes": false,
      "Nom composé d'une personne": false,
      "Fait partie du top 10 des stations les plus fréquentées": false,
      "Commence par une voyelle": false,
      "Ne contient pas la lettre A": false,
      "Ne contient pas la lettre E": false,
      "Ne contient pas la lettre I": false,
      "Contient la lettre Y": false,
      "Contient des lettres doublées": true,
      "Nom commençant par la lettre L": false,
      "Nom en un seul mot": false,
      "Correspondancevec un parking relais": true,
      "Moins d'1km d'un campus universitaire": false,
      "Moins d'1km d'un centre commercial": false,
      "Moins d'1km d'un hôpital public": false,
      "Moins d'1km d'un parc / jardin": false
    }
  },
  {
    "name": "Atalante",
    "line": "B",
    "props": {
      "Correspondance avec un Chronosbus": true,
      "Terminus d'une ligne de Métro ou d'un Chronobus ": false,
      "Station aérienne": true,
      "Station au sud de la Vilaine": false,
      "Station au nord de la Vilaine": true,
      "Station hors Rennes": true,
      "Station à Rennes": false,
      "Nom composé d'une personne": false,
      "Fait partie du top 10 des stations les plus fréquentées": false,
      "Commence par une voyelle": true,
      "Ne contient pas la lettre A": false,
      "Ne contient pas la lettre E": false,
      "Ne contient pas la lettre I": true,
      "Contient la lettre Y": false,
      "Contient des lettres doublées": false,
      "Nom commençant par la lettre L": false,
      "Nom en un seul mot": true,
      "Correspondancevec un parking relais": false,
      "Moins d'1km d'un campus universitaire": true,
      "Moins d'1km d'un centre commercial": false,
      "Moins d'1km d'un hôpital public": false,
      "Moins d'1km d'un parc / jardin": false
    }
  },
  {
    "name": "Beaulieu-Université",
    "line": "B",
    "props": {
      "Correspondance avec un Chronosbus": false,
      "Terminus d'une ligne de Métro ou d'un Chronobus ": false,
      "Station aérienne": true,
      "Station au sud de la Vilaine": false,
      "Station au nord de la Vilaine": true,
      "Station hors Rennes": false,
      "Station à Rennes": true,
      "Nom composé d'une personne": false,
      "Fait partie du top 10 des stations les plus fréquentées": true,
      "Commence par une voyelle": false,
      "Ne contient pas la lettre A": false,
      "Ne contient pas la lettre E": false,
      "Ne contient pas la lettre I": false,
      "Contient la lettre Y": false,
      "Contient des lettres doublées": false,
      "Nom commençant par la lettre L": false,
      "Nom en un seul mot": false,
      "Correspondancevec un parking relais": false,
      "Moins d'1km d'un campus universitaire": true,
      "Moins d'1km d'un centre commercial": false,
      "Moins d'1km d'un hôpital public": false,
      "Moins d'1km d'un parc / jardin": false
    }
  },
  {
    "name": "Joliot-Curie - Chateaubriand",
    "line": "B",
    "props": {
      "Correspondance avec un Chronosbus": true,
      "Terminus d'une ligne de Métro ou d'un Chronobus ": false,
      "Station aérienne": false,
      "Station au sud de la Vilaine": false,
      "Station au nord de la Vilaine": true,
      "Station hors Rennes": false,
      "Station à Rennes": true,
      "Nom composé d'une personne": true,
      "Fait partie du top 10 des stations les plus fréquentées": false,
      "Commence par une voyelle": false,
      "Ne contient pas la lettre A": false,
      "Ne contient pas la lettre E": false,
      "Ne contient pas la lettre I": false,
      "Contient la lettre Y": false,
      "Contient des lettres doublées": false,
      "Nom commençant par la lettre L": false,
      "Nom en un seul mot": false,
      "Correspondancevec un parking relais": false,
      "Moins d'1km d'un campus universitaire": true,
      "Moins d'1km d'un centre commercial": false,
      "Moins d'1km d'un hôpital public": false,
      "Moins d'1km d'un parc / jardin": true
    }
  },
  {
    "name": "Les Gayeulles",
    "line": "B",
    "props": {
      "Correspondance avec un Chronosbus": false,
      "Terminus d'une ligne de Métro ou d'un Chronobus ": false,
      "Station aérienne": false,
      "Station au sud de la Vilaine": false,
      "Station au nord de la Vilaine": true,
      "Station hors Rennes": false,
      "Station à Rennes": true,
      "Nom composé d'une personne": false,
      "Fait partie du top 10 des stations les plus fréquentées": false,
      "Commence par une voyelle": false,
      "Ne contient pas la lettre A": false,
      "Ne contient pas la lettre E": false,
      "Ne contient pas la lettre I": true,
      "Contient la lettre Y": true,
      "Contient des lettres doublées": true,
      "Nom commençant par la lettre L": true,
      "Nom en un seul mot": false,
      "Correspondancevec un parking relais": true,
      "Moins d'1km d'un campus universitaire": false,
      "Moins d'1km d'un centre commercial": false,
      "Moins d'1km d'un hôpital public": false,
      "Moins d'1km d'un parc / jardin": true
    }
  },
  {
    "name": "Gros-Chêne",
    "line": "B",
    "props": {
      "Correspondance avec un Chronosbus": true,
      "Terminus d'une ligne de Métro ou d'un Chronobus ": false,
      "Station aérienne": false,
      "Station au sud de la Vilaine": false,
      "Station au nord de la Vilaine": true,
      "Station hors Rennes": false,
      "Station à Rennes": true,
      "Nom composé d'une personne": false,
      "Fait partie du top 10 des stations les plus fréquentées": false,
      "Commence par une voyelle": false,
      "Ne contient pas la lettre A": true,
      "Ne contient pas la lettre E": false,
      "Ne contient pas la lettre I": true,
      "Contient la lettre Y": false,
      "Contient des lettres doublées": false,
      "Nom commençant par la lettre L": false,
      "Nom en un seul mot": false,
      "Correspondancevec un parking relais": false,
      "Moins d'1km d'un campus universitaire": true,
      "Moins d'1km d'un centre commercial": false,
      "Moins d'1km d'un hôpital public": false,
      "Moins d'1km d'un parc / jardin": false
    }
  },
  {
    "name": "Jules Ferry",
    "line": "B",
    "props": {
      "Correspondance avec un Chronosbus": true,
      "Terminus d'une ligne de Métro ou d'un Chronobus ": false,
      "Station aérienne": false,
      "Station au sud de la Vilaine": false,
      "Station au nord de la Vilaine": true,
      "Station hors Rennes": false,
      "Station à Rennes": true,
      "Nom composé d'une personne": true,
      "Fait partie du top 10 des stations les plus fréquentées": true,
      "Commence par une voyelle": false,
      "Ne contient pas la lettre A": true,
      "Ne contient pas la lettre E": false,
      "Ne contient pas la lettre I": true,
      "Contient la lettre Y": true,
      "Contient des lettres doublées": true,
      "Nom commençant par la lettre L": false,
      "Nom en un seul mot": false,
      "Correspondancevec un parking relais": false,
      "Moins d'1km d'un campus universitaire": true,
      "Moins d'1km d'un centre commercial": true,
      "Moins d'1km d'un hôpital public": false,
      "Moins d'1km d'un parc / jardin": true
    }
  },
  {
    "name": "Saint-Germain",
    "line": "B",
    "props": {
      "Correspondance avec un Chronosbus": false,
      "Terminus d'une ligne de Métro ou d'un Chronobus ": false,
      "Station aérienne": false,
      "Station au sud de la Vilaine": false,
      "Station au nord de la Vilaine": true,
      "Station hors Rennes": false,
      "Station à Rennes": true,
      "Nom composé d'une personne": true,
      "Fait partie du top 10 des stations les plus fréquentées": true,
      "Commence par une voyelle": false,
      "Ne contient pas la lettre A": false,
      "Ne contient pas la lettre E": false,
      "Ne contient pas la lettre I": false,
      "Contient la lettre Y": false,
      "Contient des lettres doublées": false,
      "Nom commençant par la lettre L": false,
      "Nom en un seul mot": false,
      "Correspondancevec un parking relais": false,
      "Moins d'1km d'un campus universitaire": false,
      "Moins d'1km d'un centre commercial": true,
      "Moins d'1km d'un hôpital public": false,
      "Moins d'1km d'un parc / jardin": true
    }
  },
  {
    "name": "Colombier",
    "line": "B",
    "props": {
      "Correspondance avec un Chronosbus": true,
      "Terminus d'une ligne de Métro ou d'un Chronobus ": false,
      "Station aérienne": false,
      "Station au sud de la Vilaine": true,
      "Station au nord de la Vilaine": false,
      "Station hors Rennes": false,
      "Station à Rennes": true,
      "Nom composé d'une personne": false,
      "Fait partie du top 10 des stations les plus fréquentées": true,
      "Commence par une voyelle": false,
      "Ne contient pas la lettre A": true,
      "Ne contient pas la lettre E": false,
      "Ne contient pas la lettre I": false,
      "Contient la lettre Y": false,
      "Contient des lettres doublées": false,
      "Nom commençant par la lettre L": false,
      "Nom en un seul mot": true,
      "Correspondancevec un parking relais": false,
      "Moins d'1km d'un campus universitaire": false,
      "Moins d'1km d'un centre commercial": true,
      "Moins d'1km d'un hôpital public": false,
      "Moins d'1km d'un parc / jardin": false
    }
  },
  {
    "name": "Mabilais",
    "line": "B",
    "props": {
      "Correspondance avec un Chronosbus": false,
      "Terminus d'une ligne de Métro ou d'un Chronobus ": false,
      "Station aérienne": false,
      "Station au sud de la Vilaine": true,
      "Station au nord de la Vilaine": false,
      "Station hors Rennes": false,
      "Station à Rennes": true,
      "Nom composé d'une personne": false,
      "Fait partie du top 10 des stations les plus fréquentées": false,
      "Commence par une voyelle": false,
      "Ne contient pas la lettre A": false,
      "Ne contient pas la lettre E": true,
      "Ne contient pas la lettre I": false,
      "Contient la lettre Y": false,
      "Contient des lettres doublées": false,
      "Nom commençant par la lettre L": false,
      "Nom en un seul mot": true,
      "Correspondancevec un parking relais": false,
      "Moins d'1km d'un campus universitaire": false,
      "Moins d'1km d'un centre commercial": true,
      "Moins d'1km d'un hôpital public": false,
      "Moins d'1km d'un parc / jardin": false
    }
  },
  {
    "name": "Cleunay",
    "line": "B",
    "props": {
      "Correspondance avec un Chronosbus": false,
      "Terminus d'une ligne de Métro ou d'un Chronobus ": false,
      "Station aérienne": false,
      "Station au sud de la Vilaine": true,
      "Station au nord de la Vilaine": false,
      "Station hors Rennes": false,
      "Station à Rennes": true,
      "Nom composé d'une personne": false,
      "Fait partie du top 10 des stations les plus fréquentées": false,
      "Commence par une voyelle": false,
      "Ne contient pas la lettre A": false,
      "Ne contient pas la lettre E": false,
      "Ne contient pas la lettre I": true,
      "Contient la lettre Y": true,
      "Contient des lettres doublées": false,
      "Nom commençant par la lettre L": false,
      "Nom en un seul mot": true,
      "Correspondancevec un parking relais": false,
      "Moins d'1km d'un campus universitaire": false,
      "Moins d'1km d'un centre commercial": true,
      "Moins d'1km d'un hôpital public": false,
      "Moins d'1km d'un parc / jardin": false
    }
  },
  {
    "name": "La Courrouze",
    "line": "B",
    "props": {
      "Correspondance avec un Chronosbus": false,
      "Terminus d'une ligne de Métro ou d'un Chronobus ": false,
      "Station aérienne": false,
      "Station au sud de la Vilaine": true,
      "Station au nord de la Vilaine": false,
      "Station hors Rennes": true,
      "Station à Rennes": false,
      "Nom composé d'une personne": false,
      "Fait partie du top 10 des stations les plus fréquentées": false,
      "Commence par une voyelle": false,
      "Ne contient pas la lettre A": false,
      "Ne contient pas la lettre E": false,
      "Ne contient pas la lettre I": true,
      "Contient la lettre Y": false,
      "Contient des lettres doublées": true,
      "Nom commençant par la lettre L": true,
      "Nom en un seul mot": false,
      "Correspondancevec un parking relais": false,
      "Moins d'1km d'un campus universitaire": false,
      "Moins d'1km d'un centre commercial": false,
      "Moins d'1km d'un hôpital public": false,
      "Moins d'1km d'un parc / jardin": false
    }
  },
  {
    "name": "Saint-Jacques - Gaité",
    "line": "B",
    "props": {
      "Correspondance avec un Chronosbus": true,
      "Terminus d'une ligne de Métro ou d'un Chronobus ": true,
      "Station aérienne": false,
      "Station au sud de la Vilaine": true,
      "Station au nord de la Vilaine": false,
      "Station hors Rennes": true,
      "Station à Rennes": false,
      "Nom composé d'une personne": true,
      "Fait partie du top 10 des stations les plus fréquentées": false,
      "Commence par une voyelle": false,
      "Ne contient pas la lettre A": false,
      "Ne contient pas la lettre E": false,
      "Ne contient pas la lettre I": false,
      "Contient la lettre Y": false,
      "Contient des lettres doublées": false,
      "Nom commençant par la lettre L": false,
      "Nom en un seul mot": false,
      "Correspondancevec un parking relais": true,
      "Moins d'1km d'un campus universitaire": false,
      "Moins d'1km d'un centre commercial": false,
      "Moins d'1km d'un hôpital public": false,
      "Moins d'1km d'un parc / jardin": false
    }
  }
];